"""Generate a self-contained resolution Workflow script with the grant batch EMBEDDED as a const
(avoids the fragile large-args path). Usage: python gen_resolution_workflow.py <grants.json> <out.js>
The grants.json is a list of {grant_id, acronym, host_entity, pi_name, scheme, start_year, panel, abstract}."""
import os
import sys
import json

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lib_erc

lib_erc.setup_stdout()
in_json = sys.argv[1] if len(sys.argv) > 1 else "outputs/residual_100c.json"
out_js = sys.argv[2] if len(sys.argv) > 2 else "workflows/run_resolution.workflow.js"
MODEL = sys.argv[3] if len(sys.argv) > 3 else "sonnet"
MAX_SEARCHES = int(sys.argv[4]) if len(sys.argv) > 4 else 3

import re
_CTRL = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")


def _clean(v):
    if isinstance(v, str):
        return _CTRL.sub(" ", v).strip()
    if isinstance(v, dict):
        return {k: _clean(x) for k, x in v.items()}
    if isinstance(v, list):
        return [_clean(x) for x in v]
    return v


items = _clean(json.load(open(in_json, encoding="utf-8")))
# ensure_ascii=True keeps the embedded literal pure-ASCII (accents become \uXXXX) — no control chars,
# no approval-dialog issues; the model still receives the correct accented text at runtime.
embedded = json.dumps(items, ensure_ascii=True)

js = '''// AUTO-GENERATED by gen_resolution_workflow.py — do not edit by hand.
// Resolve ERC grants -> French host lab via capped web search (Sonnet, general-purpose agents).
export const meta = {
  name: 'resolve-erc-labs',
  description: 'Resolve ERC grants to French host lab (UMR/tutelles/city) via capped web search — Sonnet',
  phases: [{ title: 'Sonnet' }],
}
const SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['grant_id', 'resolved_lab', 'tutelles', 'city', 'confidence', 'source_url'],
  properties: {
    grant_id: { type: 'string' },
    resolved_lab: { type: ['string', 'null'] },
    tutelles: { type: 'array', items: { type: 'string' } },
    city: { type: ['string', 'null'] },
    confidence: { type: 'number' },
    source_url: { type: ['string', 'null'] },
  },
}
const items = __ITEMS__
const prompt = (g) => `Task: identify the FRENCH research lab (UMR/unite) where this ERC grant's principal investigator actually works — NOT the legal employer (CNRS/INSERM/CEA/Inria/INRAE). Also its supervising institutions (tutelles/cotutelles) and city.

Grant ${g.acronym} — ERC ${g.scheme} ${g.start_year}. Legal host: ${g.host_entity}.${g.pi_name ? ' PI: ' + g.pi_name + '.' : ''} Panel: ${g.panel || ''}.
Abstract: ${(g.abstract || '').slice(0, 200)}

Method: at most __SR__ web searches (acronym + "ERC" + host; or PI name + "laboratoire"; or a CNRS/INSERM ERC-laureate press release). Be efficient; minimize reasoning tokens.

Output ONLY compact JSON (no prose): {"grant_id":"${g.grant_id}","resolved_lab":"<lab>","tutelles":["<inst>"],"city":"<city>","confidence":<0-1>,"source_url":"<url>"}
If not found: resolved_lab=null, confidence<=0.3.`

const results = await parallel(items.map((g) => () =>
  agent(prompt(g), {
    label: `__MODEL__:${g.grant_id}`, phase: 'Resolve',
    agentType: 'general-purpose', model: '__MODEL__', effort: 'low', schema: SCHEMA,
  }).then((r) => ({ ...r, grant_id: g.grant_id, source_tier: 'llm-__MODEL__' }))
))
return results.filter(Boolean)
'''.replace("__ITEMS__", embedded).replace("__MODEL__", MODEL).replace("__SR__", str(MAX_SEARCHES))

os.makedirs(os.path.dirname(out_js), exist_ok=True)
# newline="\n": avoid Windows CRLF — the \r bytes are flagged as control chars by the approval dialog
open(out_js, "w", encoding="utf-8", newline="\n").write(js)
print(f"wrote {out_js} with {len(items)} grants embedded ({len(js)//1024} KB)")
